/*********************************************************************************/
/* GPSTurbo                                                                      */
/*                                                                               */
/* Programmed by Kevin Pickell                                                   */
/*                                                                               */
/* http://www.scale18.com/cgi-bin/page/gpsturbo.html                             */
/*                                                                               */
/*    GPSTurbo is free software; you can redistribute it and/or modify           */
/*    it under the terms of the GNU General Public License as published by       */
/*    the Free Software Foundation; version 2.                                   */
/*                                                                               */
/*    GPSTurbo is distributed in the hope that it will be useful,                 */
/*    but WITHOUT ANY WARRANTY; without even the implied warranty of             */
/*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              */
/*    GNU General Public License for more details.                               */
/*                                                                               */
/*    http://www.gnu.org/licenses/gpl.txt                                        */
/*                                                                               */
/*    You should have received a copy of the GNU General Public License          */
/*    along with GPSTurbo; if not, write to the Free Software                    */
/*    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA */
/*                                                                               */
/*********************************************************************************/

char xtabstart[]={"<TABLE CELLPADDING=0 CELLSPACING=0><TR><TD><IMG SRC=\"geoart/tsl.gif\" CLASS=\"EDGE\" ALT=\" \"></TD><TD ALIGN=CENTER VALIGN=MIDDLE CLASS=\"TSB\">"};
char xtabend[]={"</TD><TD><IMG SRC=\"geoart/tsr.gif\" CLASS=\"EDGE\" ALT=\" \"></TD></TR></TABLE>"};
char xgroupstart[]={"<table border=1 cellpadding=4 cellspacing=0><tr><td>"};
char xgroupend[]={"</td></tr></table>"};
char xcolstart[]={"<td CLASS=\"FB\">"};
char xcolend[]={"</td>"};

char helpstart[]={
	"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">"
	"<html><head><title>GPS Turbo - Help</title></head>"
	"<STYLE TYPE=\"text/css\"><!--\r\n"
	"BODY{color:black;font-size:84%;font-family: 'Verdana', sans-serif;}TABLE{color:black;font-size:100%;font-family: 'Verdana', sans-serif;}"
	".TSB{background-image:url(\"geoart/tsb.gif\");height: 19px;color:white;font-weight:700;white-space:nowrap;font-size:100%;font-family: 'Verdana', sans-serif;}"
	".FB{background-image:url(\"geoart/fb.gif\");height: 15px;color:white;font-weight:700;white-space:nowrap;font-size:100%;font-family: 'Verdana', sans-serif;}"
	".EDGE {width:4px;height:19px}"
	"--></STYLE>"
	"<body>"};

char helpend[]={
	"</body></html>"};

char help[]={
	"<xTABSTART>GPSTurbo Credits<xTABEND>"
	"<xGROUPSTART>"
	"<CREDITS>"
	"<xGROUPEND>"
	"<BR><BR>"
	"<xTABSTART>GPSTurbo<xTABEND>"
	"<xGROUPSTART>"
	"GPSTurbo is a program for Geocachers that allows them to manage and plan their Geocaching outings.<BR>"
	"A quick overview of features include:<BR>"
	"Loading of Geocache waypoints from a GPX file, or any other file format supported by GPSBabel.<BR>"
	"Viewing Geocache Waypoints overlayed onto various maps<BR>"
	"Uploading and Downloading of waypoints and tracks to your GSPr<BR>"
	"Planning of Routes<BR>"
	"Printing of Maps and Waypoint lists<BR>"
	"Built in scripting language to automate repetitive tasks<BR>"
	"<xGROUPEND>"
	"<BR><BR>"

	"<xTABSTART>Main Menu<xTABEND>"
	"<xGROUPSTART>"
	"<table border=1 cellpadding=4 cellspacing=0>"
	"<tr><xCOLSTART>Menu Entry<xCOLEND><xCOLSTART>Function<xCOLEND></tr>"
	"<tr><td>Load GPX file</td><td>"
	"A Loadfile requestor will appear for you to select the file to load. "
	"Once you have selected a file then the <B>LoadSettings</B> panel will appear. "
	"This panel allows you to either Load the Waypoints or Load the Found flags into a UserTick field. "
	"If you are loading the Waypoints then you can input a database name to assign the Waypoints to, you can also limit the number of Logs imported using the input boxes ( no value means unlimited ). "
	"If you are loading the Found status into a UserTick field then you select the field to load into and you can assign a hint that will appear when the mouse pointer is left hovering over the column header. "
	"If the file contained any <B>Tracks</B> then a list of track will be shown, just tick the ones you wish to load."
	"</td></tr>"
	"<tr><td>Save GPX file</td><td>"
	"A Savefile requestor will appear for you to select the location and filename to save as. "
	"If you have any tracks then a requestor will also appear and you can select any tracks that you want saved as well. "
	"The current filtered waypoint list will then be saved along with any selected tracks."
	"</td></tr>"
	"<tr><td>Load As ...</td><td>"
	"A Loadfile requestor will appear for you to select the file to load. "
	"Then a requestor will appear for you to select the file format. The list includes all of the file types that GPSBabel understands. "
	"Once you have selected a file and format then the <B>LoadSettings</B> panel will appear. "
	"This panel allows you to either Load the Waypoints or Load the Found flags into a UserTick field. "
	"If you are loading the Waypoints then you can input a database name to assign the Waypoints to, you can also limit the number of Logs imported using the input boxes ( no value means unlimited ). "
	"If you are loading the Found status into a UserTick field then you select the field to load into and you can assign a hint that will appear when the mouse pointer is left hovering over the column header."
	"If the file contained any <B>Tracks</B> then a list of track will be shown, just tick the ones you wish to load."
	"</td></tr>"
	"<tr><td>Save As ...</td><td>"
	"A Savefile requestor will appear for you to select the location and filename to save as. "
	"Then a requestor will appear for you to select the file format. The list includes all of the file types that GPSBabel understands. "
	"If you have any tracks then a requestor will also appear and you can select any tracks that you want saved as well. "
	"The current filtered waypoint list will then be saved along with any selected tracks."
	"</td></tr>"
	"<tr><td>Rename Database</td><td>"
	"Use this function to rename waypoints from one database name to another."
	"</td></tr>"
	"<tr><td>Remove Stale Waypoints</td><td>"
	"This function will display a table showing the number of waypoints with each unique generated date. "
	"Beside each entry in this table is a tickbox to select all waypoints with that date. Just tick the lines that you wish to delete and it will remove all waypoints with the selected dates."
	"</td></tr>"
	"<tr><td>Print Table</td><td>"
	"This function is used to print the current filtered waypoint results as a table. "
	"Currently it only prints one page wide, this may be fixed in the future."
	"</td></tr>"
	"<tr><td>Print Map</td><td>"
	"This function is used to print a Map centered on the current position shown. "
	"The print preview requestor will appear and will allow panning of the area to print. "
	"The print function can print from 1 to 10 pages wide and 1 to 10 pages tall. "
	"There are a bunch of other printing options on the print preview panel."
	"You can also print waypoint information along the right edge of the map. When selected you can adjust the width of the edge and you can customize what information you would like to appear along the edge. This can be very handy for showing waypoint hints. If there are more lines than can fit on the page then the extra lines will not appear."
	"</td></tr>"
	"<tr><td>Save Bitmap</td><td>"
	"This function is used to data-mine an area of the map and save it as a Jpg Image. "
	"Here are the steps required.<BR>"
	"1) Right click on the map at the desired position and select <B>Set Upper Left Corner for Map Select</B>.<BR>"
	"2) Right click on the map at the desired position and select <B>Set Lower Right Corner for Map Select</B>.<BR>"
	"3) If desired you can zoom in or out to the desired level.<BR>"
	"4) Now from the main menu select <B>Save Bitmap</B>.<BR>"
	"5) A Savefile requestor will appear for you to select the location and filename to save as.<BR>"
	"6) Wait... This can take a while if you are saving a large image.<BR>"
	"7) To clear the selected range from the map Right Click on the map and select <B>Clear Map Select area</B>"
	"</td></tr>"
	"<tr><td>View Filtered Cache Pages in Browser</td><td>"
	"This will show the Geocache waypoint descriptions for all of the Waypoints in the Filtered Results List in your browser. "
	"You can then print them from your browser, most browsers will allow you to print them at 1/2 or 1/4 size to save paper. "
	"</td></tr>"
	"<tr><td>View Filtered Cache Pages in Window</td><td>"
	"This is the same as the previous line except that they are shown in a window within GPSTurbo. Note: The GPSTurbo HTML renderer is currently not finished so it may not appear correctly at this time."
	"</td></tr>"
	"<tr><td>Credits</td><td>"
	"A Popup window will appear showing the Build version and other information." 
	"</td></tr>"
	"<tr><td>View Help Page in Browser</td><td>"
	"This will open this help page in your current browser."
	"</td></tr>"
	"<tr><td>View Help Page in Browser</td><td>"
	"This is the same as the previous line except that they are shown in a window within GPSTurbo. Note: The GPSTurbo HTML renderer is currently not finished so it may not appear correctly at this time."
	"</td></tr>"
	"<tr><td>Quit</td><td>"
	"Exit the program and save all changes and settings."
	"</td></tr>"
	"</table>"
	"<xGROUPEND>"
	"<BR><BR>"
	"<xTABSTART>Filtered/Map<xTABEND>"
	"<xGROUPSTART>"
	"<B>Current Map</B><BR>"
	"This pulldown is used to select the desired map."
	"<BR><BR><B>Zoom</B><BR>"
	"This pull down can be used to quickly change the zoom level.."
	"<BR><BR><B>Zoom In / Zoom Out</B><BR>"
	"These buttons are used to zoom in and out of the current map. You can also use the keyboard <B>CTRL +</B> or <B>Ctrl -</B> to zoom in and out."
	"<BR><BR><B>Online</B><BR>"
	"This tickbox is used to tell GPSTurbo if you are currently online.<BR>"
	"When online, GPSTurbo will try and download map tiles for online maps if they are not already in the map tile cache. "
	"<BR><BR><B>Map Position under Mouse</B><BR>"
	"This will show the current Lat / Lon position on the map under the mouse pointer."
	"<BR><BR><B>Current Filter / Current Database / Reverse / Search String</B><BR>"
	"These settings are used to select the filtered waypoints from the full waypoint list, which are then shown in the table below.<BR>"
	"To select using a filter, use the pull down menu to select the desired filter. To show all waypoints select the first entry in the filter pulldown (<B>Show All</B>) and make sure the <B>Search String</B> inputbox is empty. "
	"To only search in a particular database just use the <B>Current Database</B> pulldown to select the desired database. "
	"To show the Reverse results of any search just select the <B>Reverse</B> tickbox."
	"To search the filtered results for a text string, just type the string to look for in the <B>Search String</B> box and press return. "
	"<BR><BR><B>Filtered Results</B><BR>"
	"This shows the number of waypoints that match the current filter and the total number of waypoints in the full waypoint list."
	"<BR><BR><B>Current Center Position</B><BR>"
	"You can set a current center position by Right Clicking on the Map and select this entry from the popup menu. This box will then show that current center position. "
	"The <B>Dist</B> column in the table below will show the distance between the current center position and the position for each waypoint entry in the table."
	"<BR><BR><B>Near Distance</B><BR>"
	"You can set a near distance ( it is in the current map units that you can see in the bottom right corner of the map and if desired you can change it on the draw settings page ). "
	"The <B>Near</B> column in the table below will then show the number of waypoints ( in the filtered results ) that are within that distance of each waypoint. If desired you can then sort the filtered results table by the <B>Near</B> column and this can be helpful for finding areas with a large concentation of waypoints that are close to each other."
	"<BR><BR><B>GPS18 - Connect / Track / Position</B><BR>"
	"This is still under development, when selected GPSTurbo will connect to a Garmin GPS18 and track your current position. "
	"Selecting the first tickbox (<B>Connect</B>) will initialize communication with the GPS18 and when connected will show the current position in the <B>Position</B> boxes. "
	"Selecting the second tickbox (<B>Track</B>) will make the map follow the GPS18's current position."
	"<BR><BR><B>Filtered Waypoint Results Table</B><BR>"
	"This table shows the current filtered results from the full waypoint list.<BR>"
	"Double clicking on a label on the map will move the cursor on the filtered results table to that waypoint. "
	"Right click on the waypoint name for a options menu. Double click on the waypoint name to center the map at that position.<BR>"
	"You can adjust the column widths by clicking on the column headers and dragging left or right. "
	"You can change column width, hide and show columns and reorder them by right clicking on the top left table box and using the popup menu to make the desired changes.<BR>"
	"Right clicking on the column header will open a popup menu with the following options:<BR>"

	"<table border=1 cellpadding=4 cellspacing=0>"
	"<tr><xCOLSTART>Menu Entry<xCOLEND><xCOLSTART>Function<xCOLEND></tr>"
	"<tr><td>Sort&nbsp;Ascending<BR>Sort&nbsp;Descending</td><td>This will reset the sorting and sort based on the column selected.</td></tr>"
	"<tr><td>Hide Column</td><td>Select this entry to hide the column.</td></tr>"
	"<tr><td>Secondary&nbsp;Sort&nbsp;Ascending<BR>Secondary&nbsp;Sort&nbsp;Descending</td><td>This will append the sort to the previously set sort columns. For example, if you want to sort the filtered results by Difficulty, then Terrain, then Type, then Name. Right Click on <B>Difficulty</B>, then select <B>Sort Ascending</B>, then Right Click on <B>Terrain</B> and select <B>Secondary Sort Ascending</B>, then Right Click on <B>Name</B> and select <B>Secondary Sort Ascending</B>.</td></tr>"
	"<tr><td>UserTick Columns Only:<BR>Clear All<BR>Set All<BR>Set Column Hint</td><td>"
	"A common use for the UserTick flags is to load the Found flags for other cachers who you regularly do group caching with. <BR>"
	"Use these commands to Clear all ticks, set all ticks or set the hint for the selected column. <BR>"
	"The column hint will appear when the mouse is hovered over the particular column header and would typically be set to the Cacher's Name whose Founds have been assigned to that column.</td></tr>"
	"</table>"
	"<BR><BR><B>Drag Bar</B><BR>"
	"Click and move the Drag Bar up and down to adjust the relative sizes of the Table and Map."
	"<BR><BR><B>Map</B><BR>"
	"This is the area where the current map is displayed. <BR>"
	"Right Clicking on the map will bring up a popup menu.<BR>"
	"If there are multiple waypoint labels under the mouse pointer position, then a menu will appear showing all Waypoint names near the mouse pointer for you to select the desired one. <BR>"
	"<table border=1 cellpadding=4 cellspacing=0>"
	"<tr><xCOLSTART>Menu Entry<xCOLEND><xCOLSTART>Function<xCOLEND></tr>"
	"<tr><td>Set as Center</td><td>"
	"Selecting this will set the <B>Current Center Position</B> to the position on the map. If you clicked on a Waypoint label then the position is set to the Waypoint's position."
	"</td></tr>"
	"<tr><td>Select</td><td>"
	"This will select the Waypoint named at the top of the popup menu."
	"</td></tr>"
	"<tr><td>View Webpage in browser</td><td>"
	"This will show the offline webpage the Waypoint named at the top of the popup menu in a Browser."
	"</td></tr>"
	"<tr><td>View Webpage in window</td><td>"
	"This is the same as the previous line except that they are shown in a window within GPSTurbo. Note: The GPSTurbo HTML renderer is currently not finished so it may not appear correctly at this time."
	"</td></tr>"
	"<tr><td>Add to Route</td><td>"
	"This will add the Waypoint named at the top of the popup menu to the current route."
	"</td></tr>"
	"<tr><td>Toggle Found</td><td>"
	"This will toggle the Found field for the Waypoint named at the top of the popup menu."
	"</td></tr>"
	"<tr><td>Toggle User1 Ticked</td><td>"
	"This will toggle the UserTick1 field for the Waypoint named at the top of the popup menu."
	"</td></tr>"
	"<tr><td>Toggle Not Available</td><td>"
	"This will toggle the Not Available field for the Waypoint named at the top of the popup menu."
	"</td></tr>"
	"<tr><td>Clear Map Select area</td><td>"
	"This will clear the current Map Select Area and stop drawing the select area rectangle on the map."
	"</td></tr>"
	"<tr><td>Set Upper Left Corner for Map Select</td><td>"
	"This will select the upper left corner for the map selection area."
	"</td></tr>"
	"<tr><td>Set Lower Right Corner for Map Select</td><td>"
	"This will select the lower right corner for the map selection area."
	"</td></tr>"
	"<tr><td>Add Point to Full Waypoint List</td><td>"
	"This will a new Waypoint to the Waypoint table. It will be defined as a User Type of Waypoint."
	"</td></tr>"
	"<tr><td>Select Nearest Track Section</td><td>"
	"Using the current track, this will move the cursor for the track table to the entry nearest the mouse pointer."
	"</td></tr>"
	"<tr><td>Add Point to the Current Track</td><td>"
	"This will append the point at the mouse position to the end of the current track."
	"</td></tr>"
	"<tr><td>Add [Way]Point to the Current Lines</td><td>"
	"This will append the point ( or Waypoint ) at the mouse position to the end of the current lines group."
	"</td></tr>"
	"</table>"
	"<xGROUPEND>"
	"<BR><BR>"

	"<xTABSTART>Routes<xTABEND>"
	"<xGROUPSTART>"
	"<B>Up / Dn</B><BR>"
	"These buttons are for re-ordering the waypoints in the current route. Just click on the desired row to move, then press the Up or Down buttons to move it up or down in the list.<BR><BR>"
	"<B>Auto Order</B><BR>"
	"This button will re-order the route using a <B>Traveling Salesman</B> heuristic to calculate the shortest route that connects all points in the route. It starts at the first point in the list so you need to manually move the starting point to the top of the list if it is not already there. "
	"For long routes this function can take a minute or more. Currently the distances between waypoints are a straight line with no consequence for crossing water etc. In a future version this will use road routing to calculate the distances between waypoints.<BR><BR>"
	"<B>Current Route</B><BR>"
	"This pulldown is used to select the route to be viewed or edited. To make a new route just select the first entry (<B>New Route</B>) and then add Waypoints to it. If the current route has changes made to it then you will not be able to change this pull down to another route until you either saved the changes in the current route or cancelled ( using undo ) the changes.<BR><BR>"
	"<B>Save Route</B><BR>"
	"After adding Waypoints to a <B>New Route</B> click this button to assign a name to your newly created route. . Or press to save changes to an existing route.<BR><BR>"
	"<B>Undo Changes</B><BR>"
	"This will remove all changes to the current route since it was last saved.<BR><BR>"
	"<B>Delete Route</B><BR>"
	"This will delete the current route from the list of routes.<BR><BR>"
	"<B>Rename Route</B><BR>"
	"This will allow you to change the current route's name.<BR><BR>"
	"<B>Copy Route</B><BR>"
	"This will allow you to make a copy of the current route.<BR><BR>"
	"<xGROUPEND>"
	"<BR><BR>"

	"<xTABSTART>Tracks<xTABEND>"
	"<xGROUPSTART>"
	"<B>Up / Dn</B><BR>"
	"These buttons are for re-ordering the waypoints in the current track. Just click on the desired row to move, then press the Up or Down buttons to move it up or down in the list.<BR><BR>"
	"<B>Current Track</B><BR>"
	"This pulldown is used to select the track to be viewed or edited. To make a new track just select the first entry (<B>New Track</B>) and then add Waypoints to it. If the current track has changes made to it then you will not be able to change this pull down to another track until you either saved the changes in the current track or cancelled ( using undo ) the changes.<BR><BR>"
	"<B>Save Track</B><BR>"
	"After adding Waypoints to a <B>New Track</B> click this button to assign a name to your newly created track. Or press to save changes to an existing track.<BR><BR>"
	"<B>Undo Changes</B><BR>"
	"This will remove all changes to the current track since it was last saved.<BR><BR>"
	"<B>Delete Track</B><BR>"
	"This will delete the current track from the list of tracks.<BR><BR>"
	"<B>Rename Track</B><BR>"
	"This will allow you to change the current track's name.<BR><BR>"
	"<B>Copy Track</B><BR>"
	"This will allow you to make a copy of the current track.<BR><BR>"
	"<B>Simplify Track</B><BR>"
	"This will allow you to reduce the number of points in the track. A input box will appear, just type in the number of points you want the track reduced to and it will reduce it down to that many points as best it can.<BR><BR>"
	"<B>Draw Track</B><BR>"
	"This tickbox, when selected will show the track on the main map screen.<BR><BR>"
	"<B>Track Color</B><BR>"
	"This is the color that the track will be drawn with on the main map screen.<BR><BR>"
	"<B>Double Clicking</B><BR>"
	"Double clicking on either the Lat or Lon field in the track points table will center the map on that position and switch to the main map screen.<BR><BR>"
	"<B>Creating Areas</B><BR>"
	"You can also use the tracks to create <B>Areas</B> for use in filters.<BR>For example: If you have two islands very close by and want to have a filter that only shows wayponts on one of the islands then you can do the following. "
	"Right click on the map and select <B>add point to track 'New Track'</B> and do this over and over, creating a perimiter around one of the islands ( it will assume that the last point connects back to the first). When done, save the track and call it 'island1'. Then in your desired filter, add <B>Position is inside island1</B> to the list of filter commands and the filter will now only return results inside the desired area."
	"<xGROUPEND>"
	"<BR><BR>"

	"<xTABSTART>Lines<xTABEND>"
	"<xGROUPSTART>"
	"Lines are lists of primitves that you can use to draw lines, arcs and circles as overlays on the current map. The lines draw processor starts at the top of the list of primitives and works it's way down the list. Draw primitives like Line, Circle and Arc use previously defined values for their drawing, so things like distance and radius must be defined before them in the list.<BR><BR>"
	"<B>Up / Dn</B><BR>"
	"These buttons are for re-ordering the entries in the current lines table. Just click on the desired row to move, then press the Up or Down buttons to move it up or down in the list.<BR><BR>"
	"<B>Current Lines</B><BR>"
	"This pulldown is used to select the lines group to be viewed or edited. To make a new lines group just select the first entry (<B>New Lines</B>) and then add Waypoints to it. If the current lines group has changes made to it then you will not be able to change this pull down to another lines group until you either saved the changes in the current lines group or cancelled ( using undo ) the changes.<BR><BR>"
	"<B>Save Lines</B><BR>"
	"After adding entries to the lines table <B>New Lines</B> click this button to assign a name to your newly created lines group. Or press to save changes to an existing lines group.<BR><BR>"
	"<B>Undo Changes</B><BR>"
	"This will remove all changes to the current lines group since it was last saved.<BR><BR>"
	"<B>Delete Lines</B><BR>"
	"This will delete the current lines group from the list of lines.<BR><BR>"
	"<B>Rename Lines</B><BR>"
	"This will allow you to change the current lines group's name.<BR><BR>"
	"<B>Copy Lines</B><BR>"
	"This will allow you to make a copy of the current lines group.<BR><BR>"
	"<B>Draw Lines</B><BR>"
	"This tickbox, when selected will show the lines group on the main map screen.<BR><BR>"
	"<B>Line Table Primitives</B><BR>"
	"This table shows the entries in the current lines group. To add new entries just click on the <B>*</B> on the bottom row and then change the row values as desired. To delete a row just click on the selector on the left of the row and press the delete key.<BR>"
	"After adding an entry to the table, just change the type by using the combobox in the first column.<BR><BR>"
	"<TABLE border=1 cellpadding=4 cellspacing=0>"
	"<tr><xCOLSTART>Primitive Type<xCOLEND><xCOLSTART>Value1<xCOLEND><xCOLSTART>Value2<xCOLEND><xCOLSTART>Description<xCOLEND></tr>"
	"<TR><TD><B>Waypoint</B></TD><TD>Waypoint Name</TD><TD>Unused</TD><TD>Defines a point.</TD></TR>"
	"<TR><TD><B>Point</B></TD><TD>Latitude</TD><TD>Longitude</TD><TD>Defines a point.</TD></TR>"
	"<TR><TD><B>Heading</B></TD><TD>Type</TD><TD>Value</TD><TD>Defines a heading angle.</TD></TR>"
	"<TR><TD><B>Distance</B></TD><TD>Type</TD><TD>Value</TD><TD>Defines a distance.</TD></TR>"
	"<TR><TD><B>Radius</B></TD><TD>Type</TD><TD>Value</TD><TD>Defines a radius.</TD></TR>"
	"<TR><TD><B>Project</B></TD><TD>Unused</TD><TD>Unused</TD><TD>Projects a new point from the last defined point using the last defined heading and distance.</TD></TR>"
	"<TR><TD><B>Color</B></TD><TD>Color Value</TD><TD>Unused</TD><TD>Sets a new color for drawing.</TD></TR>"
	"<TR><TD><B>Thickness</B></TD><TD>Thickness Pixels</TD><TD>Unused</TD><TD>Sets a new thickness for drawing.</TD></TR>"
	"<TR><TD><B>Line</B></TD><TD>Unused</TD><TD>Unused</TD><TD>Draws a line between the last two points using the current color and thickness.</TD></TR>"
	"<TR><TD><B>Arc</B></TD><TD>Clockwise / Counterclockwise</TD><TD>Unused</TD><TD>Draws an arc using the current color and thickness, starting at the last defined point, using the last defined radius, starting tangent to the last defined heading and going the last defined distance. Arc goes clockwise or counterclockwise depending on the selected type. Use a negative distance for having the arc starting 180 degress from the last heading. Set's the current point to the ending position of the arc, and the current heading to the ending heading.</TD></TR>"
	"<TR><TD><B>Circle</B></TD><TD>Unused</TD><TD>Unused</TD><TD>Draws an circle using the current color and thickness, centered at the last point, using the last defined radius</TD></TR>"
	"</TABLE>"
	"<xGROUPEND>"
	"<BR><BR>"

	"<xTABSTART>Filters<xTABEND>"
	"<xGROUPSTART>"
	"<B>Current Filter</B><BR>"
	"This pulldown is used to select the filter to be viewed or edited. To make a new Filter just select the first entry (<B>New Filter</B>) and then add rows to it by clicking on the bottom row in the table. If the current filter has changes made to it then you will not be able to change this pull down to another filter until you either saved the changes in the current filter or cancelled ( using undo ) the changes.<BR><BR>"
	"<B>Save Filter</B><BR>"
	"After adding rows to a <B>New Filter</B> click this button to assign a name to your newly created Filter. Or press to save changes to an existing filter.<BR><BR>"
	"<B>Undo Changes</B><BR>"
	"This will remove all changes to the current Filter since it was last saved.<BR><BR>"
	"<B>Delete Filter</B><BR>"
	"This will delete the current Filter from the list of Filters.<BR><BR>"
	"<B>Rename Filter</B><BR>"
	"This will allow you to change the current Filter's name.<BR><BR>"
	"<B>Copy Filter</B><BR>"
	"This will allow you to make a copy of the current Filter.<BR><BR>"
	"<B>Filter Entries Table</B><BR>"
	"This table shows the entries in the current filter. To add new entries just click on the <B>*</B> on the bottom row and then change the row values as desired. To delete a row just click on the selector on the left of the row and press the delete key. Each row in the filter is logically and'ed so all entries need to be <B>True</B> for a Waypoint to be in the filtered results."
	"<xGROUPEND>"
	"<BR><BR>"
	"<xTABSTART>Draw Settings<xTABEND>"
	"<xGROUPSTART>"
	"<B>Up / Dn</B><BR>"
	"These buttons are for re-ordering the label colors in the table below. Just click on the desired row to move, then press the Up or Down buttons to move it up or down in the list.<BR><BR>"
	"<B>Label Color Table</B><BR>"
	"This table is used to assign different colors to the Waypoint Labels drawn on the Map. To add new entries just click on the <B>*</B> on the bottom row and then change the row values as desired. To delete a row just click on the selector on the left of the row and press the delete key. The first column will list the filter to use and the next column will contain the color to draw the label on the map. When assigning colors to the labels the program starts at the top of this list and uses the color for the first entry that matches the selected filter. The third column is just for informational purposes and shows the number of labels that match that filter at that point in the list.<BR><BR>"
	"<B>Map Paths</B><BR>"
	"This table is used to list the paths to maps to use. You can add multiple paths to the table. If you have any Garmin IMG maps installed then typically they are installed in the <B>C:\\Garmin\\</B> directory so adding this path to the table would allow you to use these maps. You can manually edit the path fields in each table entry, or click on the <B>...</B> Button and use a file requestor to select the map directory.<BR><BR>"
	"<B>Font Size for Waypoint Labels on Map</B><BR>"
	"This is the point size to use for drawing Labels on the map.<BR><BR>"
	"<B>Number of User Ticks to show beside Label on Map</B><BR>"
	"This is how many user tick boxes are drawn to the left of the Label. (The leftmost tickbox would be UserTick1, then UserTick2 etc.)<BR><BR>"
	"<B>Waypoint Name to use on Map</B><BR>"
	"This is where you define the Label format for what will appear on the Map for each Waypoint. This string can contain static text intermixed with text from the various columns from the waypoint table. To insert text from a particular column just place a period '.' followed immediately by the column name. Use the abbreviated spelling that is used on the comumn headers of the Filtered Results table.<BR><BR>"
	"<B>Show Labels for Additional Waypoints on Map</B><BR>"
	"When ticked, Child Waypoints ( typically Parking or Trailhead Coordinates ) are also drawn on the map.<BR><BR>"
	"<B>Move overlapping Labels</B><BR>"
	"When ticked, any Labels that overlap another Label are moved down to the next available space and a line is drawn to show where the Label should have been.<BR><BR>"
	"<B>Move overlapping Labels, Maximum number of pixels</B><BR>"
	"When Labels are moved, this is the maximum distance (in pixels) to move them before giving up and drawing them at their original (overlapping) position.<BR><BR>"
	"<B>Zoom level to start drawing Labels at</B><BR>"
	"The Map Zoom level starts at 1 for the highest zoomed out level and increases as the map is zoomed in. If the zoom level is less than the number in this inputbox then Labels are not drawn on the Map.<BR><BR>"
	"<B>Distance Units</B><BR>"
	"This is used to select which type of distance units are shown in the Filtered Waypoint Results table for the <B>Dist</B> (distance from centerpoint) column, it is also the units drawn on the bottom right of the Map.<BR><BR>"
	"<xGROUPEND>"
	"<BR><BR>"

	"<xTABSTART>GPSRs<xTABEND>"
	"<xGROUPSTART>"
	"<B>GPSr Table</B><BR>"
	"Use the table to define the various GPSr settings for the GPSrs that you have.<BR><BR>"
	"<B>Current GPSr</B><BR>"
	"Use this pulldown to select the GPSr to use when Uploading or Downloading.<BR><BR>"
	"<B>Upload Waypoints to GPSr</B><BR>"
	"Press to upload the filtered waypoints to the current GPSr. "
	"If the current filtered results contain more waypoints than the current GPSr can handle it will only upload the maximum number of waypoints starting at the top of the table. For example if your GPSr can only handle 500 waypoints and your filtered results have 2600 waypoints then only the first 500 in the table will be uploaded. "
	"To force a particular area of waypoints to be uploaded you can use the <B>Set Center Point</B> function ( from the main map screen ) to set a center point to the area you wish to upload and then sort the waypoint results based on the distance from that centerpoint. That way the waypoints nearest your centerpoint will be at the top of the filtered results table and will be uploaded first. "
	"Many GPSrs do not have any error reporting back to the computer if their waypoint tables are full. After uploading it will download the points from the GPSr to verify that the points were uploaded corectly. If any points were not found then it  will list them in a popup window and you will need to manually delete old waypoints from your GPSr to free up space.<BR><BR>"
	"<B>Download Waypoints from GPSr</B><BR>"
	"Press to download waypoints from the current GPSr. Matching waypoints found in the full waypoints list will be skipped as they already exist, new waypoints will be added to the waypoints table as <B>USER</B> waypoints and named <B>USER_XXX</B> where XXX is a unique number.<BR><BR>"
	"<B>Upload Tracks to GPSr</B><BR>"
	"Press to upload <B>Tracks</B> to the current GPSr. "
	"A popup menu will appear showing all of the tracks, just tick the ones you want to upload. After uploading it will automatically download them from the GPSr to verify if they were uploaded correctly. "
	"Some GPSrs have a limit on the number of points allowed in a track so you might get an error message like <B>Track 'xxx' only the first 500 of the 2600 points were uploaded.</B> "
	"In this case you need to reduce the number of points in that track to the number that it reported. On the track page just use the <B>Simplify Track</B> button to reduce the number of points in that track.<BR><BR>"
	"<B>Download Tracks from GPSr</B><BR>"
	"Press to download <B>Tracks</B> from the current GPSr. A popup window will appear showing the tracks on the GPSr, just select the tickbox beside each track you wish to download.<br>"
	"<xGROUPEND>"
	"<BR><BR>"
	"<xTABSTART>Solver<xTABEND>"
	"<xGROUPSTART>"
	"<xTABSTART>Decode<xTABEND>"
	"<xGROUPSTART>"
	"<B>Plain Text</B><BR>"
	"Put your plain text in here to encode or if decoding then the results will be placed here.<BR><BR>"
	"<B>Encoding</B><BR>"
	"Use this pulldown to select the encoding format.<BR><BR>"
	"<B>Key</B><BR>"
	"Some encoding formats use a key, so if the one you are using does then you can type the key here.<BR><BR>"
	"<B>Encode (Plain -> Encoded) </B><BR>"
	"After typing ( or pasteing ) in some text in the plain box above and selecting an encoding method ( and key if applicable ) then pressing this button will generate the encoded text in the encoded text box below.<BR><BR>"
	"<B>Decode (Encoded -> Plain) </B><BR>"
	"After typing ( or pasteing ) in some text in the encoded box below and selecting an encoding method ( and key if applicable ) then pressing this button will generate the decoded text in the plain text box above.<BR><BR>"
	"<B>Encoded Text</B><BR>"
	"Put your encoded text in here to decode or if encoding then the results will be placed here.<BR><BR>"
	"<xGROUPEND>"
	"<xTABSTART>Project<xTABEND>"
	"<xGROUPSTART>"
	"<B>From</B><BR>"
	"Put the starting position ( Lat / Lon ) in these two boxes.<BR><BR>"
	"<B>Distance</B><BR>"
	"Put the distance in this box and select the units in the pulldown.<BR><BR>"
	"<B>Heading</B><BR>"
	"Put the heading in this box and select the heading type in the pulldown.<BR><BR>"
	"<B>Earth Model</B><BR>"
	"Although all coords are in WGS84, you can specify a different Earth Model if desired.<BR><BR>"
	"<B>Calculate</B><BR>"
	"Press to generate the projected point results.<BR><BR>"
	"<B>To</B><BR>"
	"The projected point ( Lat / Lon ) is shown in these two boxes.<BR><BR>"
	"<xGROUPEND>"
	"<xTABSTART>Distance<xTABEND>"
	"<xGROUPSTART>"
	"<B>Point A</B><BR>"
	"Put one position ( Lat / Lon ) in these two boxes.<BR><BR>"
	"<B>Point B</B><BR>"
	"Put another position ( Lat / Lon ) in these two boxes.<BR><BR>"
	"<B>Distance Units</B><BR>"
	"Select the desired distance units in the pulldown.<BR><BR>"
	"<B>Heading type</B><BR>"
	"Select the desired heading type in the pulldown.<BR><BR>"
	"<B>Earth Model</B><BR>"
	"Although all coords are in WGS84, you can specify a different Earth Model if desired.<BR><BR>"
	"<B>Calculate</B><BR>"
	"Press to generate the distance and heading between the points.<BR><BR>"
	"<B>Distance</B><BR>"
	"The distance between the the points is shown here.<BR><BR>"
	"<B>Heading A to B</B><BR>"
	"The heading from point A to B is shown here.<BR><BR>"
	"<B>Heading B to A</B><BR>"
	"The heading from point B to A is shown here.<BR><BR>"
	"<xGROUPEND>"
	"<xTABSTART>Sunrise / Sunset<xTABEND>"
	"<xGROUPSTART>"
	"<B>Location</B><BR>"
	"Put the position ( Lat / Lon ) in these two boxes.<BR><BR>"
	"<B>Day</B><BR>"
	"Put the day of the month (1-31) here.<BR><BR>"
	"<B>Month</B><BR>"
	"Select the Month using the pulldown.<BR><BR>"
	"<B>Year</B><BR>"
	"Put the desired year here.<BR><BR>"
	"<B>TimeZone</B><BR>"
	"Select the timezone for the results here using the pulldown.<BR><BR>"
	"<B>Zenith</B><BR>"
	"Select the desired Zenith, if you don't know what this is then leave it on <B>Official</B>.<BR><BR>"
	"<B>Calculate</B><BR>"
	"Press to generate the sunrise and sunnset times.<BR><BR>"
	"<B>Sunrise</B><BR>"
	"The sunrise time results will be generated here.<BR><BR>"
	"<B>Sunset</B><BR>"
	"The sunset time results will be generated here.<BR><BR>"
	"<xGROUPEND>"
	"<xGROUPEND>"
	"<BR><BR>"
	"<xTABSTART>Stickers<xTABEND>"
	"<xGROUPSTART>"
	"Stickers are sometimes used to place on geocache logbooks instead of signing them.<BR>"
	"Currently it only supports 1 label size and that is the Avery labels that are 80 stickers on a sheet ( 20 rows of 4 ), the stickers themselves are 1.75\" x .5\"<BR>"
	"You can use the primitives in the sticker table below to define your sticker art, or you can have your sticker made in advance (using your own art program like Photoshop), the size should be 350 pixels wide by 100 pixels tall and then just add one entry to the table to load the image file.<BR><BR>"
	"<B>Current Sticker</B><BR>"
	"This pulldown is used to select the Sticker to be viewed or edited. To make a new Sticker just select the first entry (<B>New Sticker</B>) and then add rows to it by clicking on the bottom row in the table. If the current Sticker has changes made to it then you will not be able to change this pull down to another Sticker until you either saved the changes in the current Sticker or cancelled ( using undo ) the changes.<BR><BR>"
	"<B>Save Sticker</B><BR>"
	"After adding rows to a <B>New Sticker</B> click this button to assign a name to your newly created Sticker. Or press to save changes to an existing sticker.<BR><BR>"
	"<B>Undo Changes</B><BR>"
	"This will remove all changes to the current Sticker since it was last saved.<BR><BR>"
	"<B>Delete Sticker</B><BR>"
	"This will delete the current Sticker from the list of Stickers.<BR><BR>"
	"<B>Rename Sticker</B><BR>"
	"This will allow you to change the current Sticker's name.<BR><BR>"
	"<B>Copy Sticker</B><BR>"
	"This will allow you to make a copy of the current Sticker.<BR><BR>"
	"<B>Print Sticker</B><BR>"
	"This will open a print preview screen showing the full page of stickers. You can then print it by clicking the print button.<BR><BR>"
	"<B>Sticker Entries Table</B><BR>"
	"This table shows the entries in the current Sticker. To add new entries just click on the <B>*</B> on the bottom row and then change the row values as desired. To delete a row just click on the selector on the left of the row and press the delete key. "
	"Each table entry is for a draw primitive object to be drawn on the label. For each table entry use the pull down menu in the first column to select the primitive type. <BR>"
	"For a text entry, select the color using the pull down, then the x & y pixel positions (w & h are not used) then the font size to use and finally the text to draw. <BR>"
	"For a image entry, set the x & y pixel positions (w & h are not used) then the size is a scale factor to resize the image then and finally the text box should contain the filename for the image. If you double click on the filename box you can use a file requestor to select the image. <BR>"
	"For a rectangle entry, select the color and then the x & y pixel positions and w & h pixels sizes for the rectangle." 
	"<xGROUPEND>"
	"<BR><BR>"

	"<xTABSTART>Basic<xTABEND>"
	"<xGROUPSTART>"
	"For scripting repetitive tasks you can write your own code using a variant of Basic called kBasic. The syntax and built-in commands are described further down in the instructions.<BR><BR>"
	"<B>Start</B><BR>"
	"Press this button to run a Basic Subroutine. When pressed, a popup menu will appear showing all <B>Public</B> Subroutines that don't take any parameters.<BR><BR>"
	"<B>Abort</B><BR>"
	"When a Basic program is running you may press Abort to stop execution.<BR><BR>"
	"<B>Source Code InputBox</B><BR>"
	"This input box is where you can write your own Basic Subroutines and Functions.<BR>"
	"<xGROUPEND>"
	"<BR><BR>"
};

